import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import 'element-plus/theme-chalk/dark/css-vars.css'
import './styles/ot-theme.css'
import './styles/ot-primary.css'
import './styles/landing.css'
import './styles/login.css'
import './styles/responsive.css'
import './styles/scroll-reveal.css'
import './styles/global.css'
import App from './App.vue'
import router from './router'

createApp(App).use(ElementPlus).use(router).mount('#app')
